on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Clona el repositorio
        uses: actions/checkout@v3

      - name: Configura Node.js  
        uses: actions/setup-node@v3
        with:
          node-version: '18' 

      - name: Instala Surge       
        run: npm install --global surge

      - name: Publicar página en Surge
        env:
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
          SURGE_DOMAIN: ${{ secrets.SURGE_DOMAIN }}
        run: |
          surge --project ./ \
                --domain $SURGE_DOMAIN \
                --token $SURGE_TOKEN
